# docker-compose.yml
# app1, version demo
# Auteur : BRULEBOIS Loïc

# Liste des services
services:

  # Front de l'application
  app1_front:
    image: httpd
    container_name: app1_front
    restart: always
    networks:
      - apps_front
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./front/www/:/usr/local/apache2/htdocs/
    labels:
      - traefik.http.routers.app1front.rule=(Host(`localhost`) && PathPrefix(`/app1/`))
      - traefik.http.middlewares.prefix-app1front.stripprefix.prefixes=/app1
      - traefik.http.routers.app1front.middlewares=prefix-app1front
      - traefik.http.routers.app1front.entrypoints=http
      - traefik.docker.network=apps_front

# Liste des réseaux
networks:

  # apps_front - 8.0.1.0/26
  apps_front:
    name: apps_front
    external: true